from selenium.webdriver.common.by import By


class MainPagePageObject:
    """Header"""
    header_elements = {
        "yandex_logo": (By.CSS_SELECTOR, "[alt='Яндекс']"),
        "game_logo": (By.XPATH, "//*[local-name()='svg' and contains(@class, 'logo-games')]"),
        "game_logo_label": (By.CSS_SELECTOR, "[alt='Игры']"),
        "navigation_game_button": (By.CSS_SELECTOR, "div.navigation a[href='/games/']"),
        "navigation_profile_button": (By.CSS_SELECTOR, "div.navigation a[href='/games/user']"),
        "search_input": (By.CSS_SELECTOR, "input[type='search']"),
        "balance_label": (By.CSS_SELECTOR, "span.portal-currency"),
        "ya_plus_button": (By.CSS_SELECTOR, "span.YaPlus__text"),
        "ya_plus_logo": (By.XPATH, "//*[local-name()='svg' and contains(@class, 'yandex-plus')]"),
        "login_button": (By.CSS_SELECTOR, "div.user-account")
    }
    find_button = (By.CSS_SELECTOR, "button.search__button")

    """Category"""
    category_elements = {
        "category_title": (By.CSS_SELECTOR, "div.categories__header"),
        "category_list": (By.CSS_SELECTOR, "ul.categories__list"),
        "category_promos_button": (By.CSS_SELECTOR, "[data-name='promos']"),
        "category_new_button": (By.CSS_SELECTOR, "[data-name='new']"),
        "category_editors_choice_button": (By.CSS_SELECTOR, "[data-name='editors_choice']"),
        "category_arcade_button": (By.CSS_SELECTOR, "[data-name='arcade']"),
        "category_action_button": (By.CSS_SELECTOR, "[data-name='action']"),
        "category_quiz_button": (By.CSS_SELECTOR, "[data-name='quiz']"),
        "category_puzzles_button": (By.CSS_SELECTOR, "[data-name='puzzles']"),
        "category_race_button": (By.CSS_SELECTOR, "[data-name='race']"),
        "category_kids_button": (By.CSS_SELECTOR, "[data-name='kids']"),
        "category_for_girls_button": (By.CSS_SELECTOR, "[data-name='for_girls']"),
        "category_applications_button": (By.CSS_SELECTOR, "[data-name='applications']"),
        "category_for_babies_button": (By.CSS_SELECTOR, "[data-name='for_babies']"),
        "category_for_boys_button": (By.CSS_SELECTOR, "[data-name='for_boys']"),
        "category_for_two_persons_button": (By.CSS_SELECTOR, "[data-name='for_two_persons']"),
        "category_games_io_button": (By.CSS_SELECTOR, "[data-name='games_io']"),
        "category_imitations_button": (By.CSS_SELECTOR, "[data-name='imitations']"),
        "category_casino_button": (By.CSS_SELECTOR, "[data-name='casino']"),
        "category_casual_button": (By.CSS_SELECTOR, "[data-name='casual']"),
        "category_cards_button": (By.CSS_SELECTOR, "[data-name='cards']"),
        "category_midcore_button": (By.CSS_SELECTOR, "[data-name='midcore']"),
        "category_tabletop_button": (By.CSS_SELECTOR, "[data-name='tabletop']"),
        "category_novels_button": (By.CSS_SELECTOR, "[data-name='novels']"),
        "category_educational_button": (By.CSS_SELECTOR, "[data-name='educational']"),
        "category_adventure_button": (By.CSS_SELECTOR, "[data-name='adventure']"),
        "category_role_button": (By.CSS_SELECTOR, "[data-name='role']"),
        "category_simulator_button": (By.CSS_SELECTOR, "[data-name='simulator']"),
        "category_sports_button": (By.CSS_SELECTOR, "[data-name='sports']"),
        "category_strategy_button": (By.CSS_SELECTOR, "[data-name='strategy']"),
        "category_tests_button": (By.CSS_SELECTOR, "[data-name='tests']"),
        "category_match3_button": (By.CSS_SELECTOR, "[data-name='match3']"),
        "category_horrors_button": (By.CSS_SELECTOR, "[data-name='horrors']"),
        "category_balloons_button": (By.CSS_SELECTOR, "[data-name='balloons']"),
        "category_economic_button": (By.CSS_SELECTOR, "[data-name='economic']")
    }

    """Tags"""
    tags_elements = {
        "tags_title": (By.CSS_SELECTOR, "div.tags__header"),
        "tags_list": (By.CSS_SELECTOR, "ul.tags__list"),
        "tag_computer_button": (By.CSS_SELECTOR, "div[title='для компьютера']"),
        "tag_desktop_button": (By.CSS_SELECTOR, "div[title='десктоп']"),
        "tag_for_teenagers_button": (By.CSS_SELECTOR, "div[title='для подростков']"),
        "tag_in_russian_button": (By.CSS_SELECTOR, "a[href*='/games/tag/na_russkom'] > div"),
        "tag_good_quality_button": (By.CSS_SELECTOR, "a[href*='/games/tag/v_khoroshem_kachestve'] > div"),
        "tag_endless_button": (By.CSS_SELECTOR, "div[title='бесконечные']"),
        "tag_attention_button": (By.CSS_SELECTOR, "a[href*='/games/tag/na_vnimanie'] > div"),
        "tag_dexterity_button": (By.CSS_SELECTOR, "a[href*='/games/tag/na_lovkost'] > div"),
        "tag_timekiller_button": (By.CSS_SELECTOR, "div[title='таймкиллер']"),
        "tag_fun_button": (By.CSS_SELECTOR, "div[title='веселье']"),
        "tag_mobile_button": (By.CSS_SELECTOR, "div[title='мобильный']"),
        "tag_simple_button": (By.CSS_SELECTOR, "div[title='простые']"),
        "tag_fascinating_button": (By.CSS_SELECTOR, "div[title='увлекательные']"),
        "tag_brain_development_button": (By.CSS_SELECTOR, "div[title='для развития мозга']"),
        "tag_full_screen_button": (By.CSS_SELECTOR, "a[href*='/games/tag/na_ves_ekran'] > div"),
        "tag_easy_button": (By.CSS_SELECTOR, "div[title='лёгкие']"),
        "tag_logical_button": (By.CSS_SELECTOR, "div[title='логические']"),
        "tag_3d_button": (By.CSS_SELECTOR, "div[title='3d']"),
        "tag_exciting_button": (By.CSS_SELECTOR, "div[title='захватывающие']"),
        "tag_player_ratings_button": (By.CSS_SELECTOR, "div[title='с рейтингом игроков']"),
        "tag_developing_button": (By.CSS_SELECTOR, "div[title='развивающие']"),
        "tag_indie_button": (By.CSS_SELECTOR, "div[title='инди']"),
        "tag_intellectual_button": (By.CSS_SELECTOR, "div[title='интеллектуальные']"),
        "tag_clickers_button": (By.CSS_SELECTOR, "div[title='кликеры']"),
        "tag_quiz_button": (By.CSS_SELECTOR, "div[title='квиз']"),
        "tag_tests_button": (By.CSS_SELECTOR, "div[title='тесты']"),
        "tag_shooting_button": (By.CSS_SELECTOR, "div[title='стрелялки']"),
        "tag_memory_button": (By.CSS_SELECTOR, "a[href*='/games/tag/na_pamiat'] > div"),
        "tag_characters_button": (By.CSS_SELECTOR, "div[title='персонажи']"),
        "tag_minecraft_button": (By.CSS_SELECTOR, "div[title='майнкрафт']"),
        "tag_challenging_button": (By.CSS_SELECTOR, "div[title='сложные']"),
        "tag_visual_button": (By.CSS_SELECTOR, "div[title='визуальные']")
    }

    """Sections"""
    game_title = (By.CSS_SELECTOR, "span.game-card__title")
    search_result_title = (By.CSS_SELECTOR, ".search-feed__title > span")
    sections_elements = {
        "editors_choice_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='editors_choice']"),
        "all_editors_choice_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='editors_choice"),
        "for_boys_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='for_boys']"),
        "all_for_boys_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='for_boys"),
        "simulator_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='simulator']"),
        "all_simulator_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='simulator"),
        "puzzles_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='puzzles']"),
        "all_puzzles_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='puzzles"),
        "casual_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='casual']"),
        "all_casual_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='casual"),
        "action_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='action']"),
        "all_action_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='action"),
        "games_io_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='games_io']"),
        "all_games_io_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='games_io"),
        "arcade_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='arcade']"),
        "all_arcade_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='arcade"),
        "race_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='race']"),
        "all_race_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='race"),
        "horrors_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='horrors']"),
        "all_horrors_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='horrors"),
        "for_girls_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='for_girls']"),
        "all_for_girls_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='for_girls"),
        "for_two_persons_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='for_two_persons']"),
        "all_for_two_persons_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='for_two_persons"),
        "tests_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='tests']"),
        "all_tests_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='tests"),
        "kids_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='kids']"),
        "all_kids_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='kids"),
        "strategy_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='strategy']"),
        "all_strategy_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='strategy"),
        "midcore_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='midcore']"),
        "all_midcore_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='midcore"),
        "quiz_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='quiz']"),
        "all_quiz_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='quiz"),
        "new_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='new']"),
        "all_new_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='new"),
        "imitations_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='imitations']"),
        "all_imitations_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='imitations"),
        "educational_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='educational']"),
        "all_educational_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='educational"),
        "adventure_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='adventure']"),
        "all_adventure_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='adventure"),
        "economic_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='economic']"),
        "all_economic_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='economic"),
        "sports_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='sports']"),
        "all_sports_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='sports"),
        "role_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='role']"),
        "all_role_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='role"),
        "tabletop_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='tabletop']"),
        "all_tabletop_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='tabletop"),
        "match3_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='match3']"),
        "all_match3_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='match3"),
        "casino_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='casino']"),
        "all_casino_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='casino"),
        "balloons_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='balloons']"),
        "all_balloons_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='balloons"),
        "cards_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='cards']"),
        "all_cards_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='cards"),
        "novels_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='novels']"),
        "all_novels_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='novels"),
        "for_babies_title": (By.CSS_SELECTOR, "a.section-header__category-link[href*='for_babies']"),
        "all_for_babies_button": (By.CSS_SELECTOR, "a.section-header__all-link[href*='for_babies"),
    }

    """Footer"""
    footer_elements = {
        "footer_container": (By.CSS_SELECTOR, ".footer"),
        "partners_container": (By.CSS_SELECTOR, ".footer__partners"),
        "shortcut_container": (By.CSS_SELECTOR, ".footer__shortcut"),
        "copyright": (By.CSS_SELECTOR, ".copyright "),
        "links": (By.CSS_SELECTOR, ".footer-links__wrap "),
    }
